### ISSUE TITLE
Refresh mobile when using carousel 

### ISSUE THREAD

**Issue by sauniakeshauvarzy** [vahidalvandi/bootstrap4-rtl#1]
hi 

I added boosttrap4-rtl to my project and my project has carousel slider.  If i opened the project to my mobile , page refresh once when the slider running.
This code created the problem 
`body{direction:rtl}`
When i deleted that code, problem was solved.

**Comment by vahidalvandi** [comment]
hi
you can change direction for carousel slider like bellow

```
<div dir="ltr" id="carousel">

</div>
```
