### ISSUE TITLE
Dropdown menu

### ISSUE THREAD

**Issue by mhdshakouri** [vahidalvandi/bootstrap4-rtl#2]
Hi.
Thanks to you for creating RTL version of the bootstrap V4.
In Dropdown menu and it's class (`.dropdown`) you should edit two property.
One : `left:0;` to `right:0`
Two: `text-align:left;` to `text-align:right;`

With best regards.

----
**UPDATE:**
The `left:0;` should be changed to the `left:unset;`

**Comment by vahidalvandi** [comment]
Hi
please send a pull request for this fix .
Thank You

**Comment by mhdshakouri** [comment]
Created and sent.

**Comment by vahidalvandi** [comment]
thank you. merged
